### ISSUE TITLE
Deployment with GitHub pages

### ISSUE THREAD

**Issue by AndreBryant** [EagleStelle/inventrackweb#1]
GH pages deployments are only for static websites. Thus, server side codes will not be executed. This project is a full-stack app. PHP codes are executed on the server side (hence, unable to access pages with `.php` extensions `405 not allowed`). Try considering other deployment platforms/ services like Heroku or Netlify.

**Comment by EagleStelle** [comment]
Thanks for letting me know about Heroku and Netlify. 

This repo is mainly on GitHub as a backup and to share with my teammates working on the site. I deployed it to GitHub Pages just to see how it looks on different devices with different resolutions and screen sizes. 

I do understand that PHP only runs on the server side, and we're using it to connect to a database, specifically MySQL. For now, though, we’re sticking with a local database and don’t plan on hosting it just yet. Thanks again for your input, it's really helpful!
